export enum SettingTaskEnum {
  // App
  APP_COLOR_SCHEMA,
  APP_THEME_SIZE,
  APP_THEME_COLOR,

  // Header
  HEADER_FIXED,
  HEADER_ENABLE_SIDEBAR_COLLAPSE,
  HEADER_ENABLE_BREADCRUMB,
  HEADER_ENABLE_FULL_SCREEN,
  HEADER_ENABLE_PAGE_RELOAD,
  HEADER_ENABLE_COLOR_SCHEMA,
  HEADER_ENABLE_MULTI_TAB,
  HEADER_ENABLE_CACHE_MULTI_TAB,

  // Menu
  MENU_MODE,
  MENU_SHOW_LOGO,
  MENU_WIDTH,
  MENU_SUB_COLLAPSE,
  MENU_UNIQUE_OPENED,
  MENU_SWITCH_PAGE_JUMP,

  // Footer
  FOOTER_ENABLE_COPYRIGHT,
  FOOTER_DATE,
  FOOTER_COMPANY,
  FOOTER_WEBSITE,
}
